language: r
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages

r-github-packages:
  - jimhester/covr

after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::coveralls(line_exclusions= c("R/sigma.R"))'
