language: r

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"  
    - _R_CHECK_TIMINGS_="0"  ## get the timing information for the examples for all of your functions
r:
  - devel
  - release
cache: packages

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libproj-dev
      - libv8-dev

r-github-packages:
  - jimhester/covr

after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::coveralls(line_exclusions= c("src/init.cpp"))'
