language: r
r:
  - devel
  - release
sudo: false
cache: packages

r-github-packages:
  - jimhester/covr

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
    
    
after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::coveralls(line_exclusions= c("src/init.cpp"))'
