#' @title Broom-tidying methods for breathtestfit
#' 
#' @description Methods to tidy the results of class \code{breathttestfit} 
#' as generated by  \code{nls_fit} or \code{nlme_fit}. Returns the fit
#' coefficients and the Maes/Ghoos t50; additional parameters should be 
#' extracted from the key/value data in breattestfit. 
#' 
#' @param x Object of class \code{breathttestfit}
#' 
#' @return A tibble/data frame with columns
#' \itemize{
#'   \item{patient_id}{Patient Id (character)}
#'   \item{group}{Treatment or patient group (character)}
#'   \item{m}{Fraction metabolized}
#'   \item{k}{Time constant (1/minutes)}
#'   \item{beta}{The so-called lag parameters, no dimension}
#'   \item{t50}{Emptying half time in minutes as calculated following Maes/Ghoos}
#' }
#' 
#' @name breathtestfit_tidiers
#' 
#' @export
tidy.breathtestfit = function(x, ...) {
  coef(x) %>% 
    dplyr::filter(parameter %in% c("m", "k", "beta", "t50"), 
                  method %in% c("exp_beta", "maes_ghoos")) %>% 
    select(-method) %>% 
    tidyr::spread(parameter, value) %>% 
    select(patient_id, group, m, k, beta, t50) 
}

#' @title Augmented prediction for breathtest fit
#' 
#' @description Broom-methods to compute predicted values from  the results 
#' of class \code{breathttestfit}  as generated by  \code{breathtestcore::nls_fit} 
#' or \code{breathtestcore::nlme_fit}.
#' 
#' 
#' @param x Object of class \code{breathttestfit}
#' @param spacing if given, time spacing of 
#' 
#' @return \code{augment} When \code{by} is NULL,  returns one row for each 
#' original observation, and column \code{fitted}.
#' When \code{by} is a positive number, it is used as a step size for
#' a sequence of minutes from 0 to the maximum value of minute in data set. 
#' One row for each new time value with is returned, with column \code{fitted}.
#' Alternatively, a vector of positive minute values can be passed to by
#'
#' @export
augment.breathtestfit = function(x, by = NULL, dose = 100, ...) {
  assertthat::assert_that(is.null(by) || length(by) > 1 || by >= 1 )
  if (is.null(by)) {
    tidy(x)  %>% 
      select(-t50) %>% 
      inner_join(x$data, by = c("patient_id", "group")) %>% 
      mutate(
        fitted = as.numeric(exp_beta(minute, dose, m, k, beta ))
      ) %>% 
      select(-m, -k, -beta)
  } else {
    if (length(by) == 1)
      minute = seq(0, max(x$data$minute), by = by)
    else
      minute = by
    tidy(x) %>%  
      rowwise %>% 
      do( 
        data_frame(
          patient_id = .$patient_id,
          group = .$group,
          minute = minute,
          fitted = as.numeric(exp_beta(minute, dose, .$m, .$k, .$beta )))
      )
  }
}


